openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      tags:
        - tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      tags:
        - tasks
      requestBody:
        description: New task to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: The created task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    put:
      summary: Update task by ID
      tags:
        - tasks
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: ID of the task to update
      requestBody:
        description: Update task text and IsDone flag
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The updated text of the message
                is_done:
                  type: boolean
                  description: Updated is_done flag
      responses:
        '200':
          description: Updated message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Message not found

    delete:
      summary: Delete existing task by ID
      tags:
        - tasks
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: ID of the task to delete
      responses:
        '204':
          description: Deleted task
        '404':
          description: Task not found
  /users:
    get:
      summary: Get all users
      tags:
        - users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      tags:
        - users
      requestBody:
        description: New user to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: The created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Update user by ID
      tags:
        - users
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: ID of user to update
      requestBody:
        description: Update user email and password
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Updated email
                password:
                  type: string
                  description: Updated password
      responses:
        '200':
          description: Updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found

    delete:
      summary: Delete existing user by ID
      tags:
        - users
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: ID of user to delete
      responses:
        '204':
          description: Deleted user
        '404':
          description: User not found

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: uint
        text:
          type: string
        is_done:
          type: boolean
      required:
        - text
    User:
      type: object
      properties:
        id:
          type: integer
          format: uint
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password